export const MKD_CITIES = [
  'Skopje',
  'Tetovo',
  'Bitola',
  'Kumanovo',
  'Prilep',
  'Ohrid',
  'Strumica',
  'Veles',
  'Chashka',
  'Shtip',
  'Kavadarci',
  'Gostivar',
  'Kochani',
  'Kichevo',
  'Struga',
  'Radovish',
  'Gevgelija',
  'Debar',
  'Kriva Palanka',
  'Sveti Nikole',
  'Negotino',
  'Delchevo',
  'Vinica',
  'Probishtip',
  'Arachinovo',
  'Berovo',
  'Kratovo',
  'Bogdanci',
  'Studenichani',
  'Sopishte',
  'Krushevo',
  'Valandovo',
  'Tearce',
  'Makedonski Brod',
  'Demir Kapija',
  'Pehchevo',
  'Novo Selo',
  'Vevchani',
  'Petrovec',
  'Lipkovo',
  'Demir Hisar',
  'Rosoman',
  'Plasnica',
  'Mogila',
  'Krivogashtani',
  'Gradsko',
  'Rankovce',
  'Jegunovce',
  'Rostusha',
  'Centar Zhupa',
  'Zelenikovo',
  'Ilinden',
  'Makedonska Kamenica',
  'Resen',
];

export const MKD_CITIES_ABBREVIATED = {
  'SK': 'Skopje',
  'TE': 'Tetovo',
  'BT': 'Bitola',
  'KU': 'Kumanovo',
  'PP': 'Prilep',
  'OH': 'Ohrid',
  'SR': 'Strumica',
  'VE': 'Veles',
  'CH': 'Chashka',
  'ST': 'Shtip',
  'KA': 'Kavadarci',
  'GV': 'Gostivar',
  'KO': 'Kochani',
  'KI': 'Kichevo',
  'SU': 'Struga',
  'RA': 'Radovish',
  'GE': 'Gevgelija',
  'DB': 'Debar',
  'KP': 'Kriva Palanka',
  'SN': 'Sveti Nikole',
  'NE': 'Negotino',
  'DE': 'Delchevo',
  'VI': 'Vinica',
  'PS': 'Probishtip',
  'ARA': 'Arachinovo',
  'BE': 'Berovo',
  'KR': 'Kratovo',
  'BOG': 'Bogdanci',
  'STU': 'Studenichani',
  'SOP': 'Sopishte',
  'KS': 'Krushevo',
  'VA': 'Valandovo',
  'TEA': 'Tearce',
  'MB': 'Makedonski Brod',
  'DK': 'Demir Kapija',
  'PE': 'Pehchevo',
  'NSE': 'Novo Selo',
  'VV': 'Vevchani',
  'PET': 'Petrovec',
  'LIP': 'Lipkovo',
  'DH': 'Demir Hisar',
  'ROS': 'Rosoman',
  'PLS': 'Plasnica',
  'MOG': 'Mogila',
  'KRG': 'Krivogashtani',
  'GRA': 'Gradsko',
  'RAN': 'Rankovce',
  'JEG': 'Jegunovce',
  'ROT': 'Rostusha',
  'CZH': 'Centar Zhupa',
  'ZEL': 'Zelenikovo',
  'ILI': 'Ilinden',
  'MK': 'Makedonska Kamenica',
  'RE': 'Resen',
}